name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: MONITOR_WEB_ID=77d791d9-4da7-447c-ab30-249a9666e1ca; __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227159495255870653985%2522%252C%2522user_unique_id%2522%253A%25227159495255870653985%2522%252C%2522timestamp%2522%253A1666949898357%257D; _ga=GA1.2.477798719.1666949901; n_mh=3x7Ok1FmXpLLPzuCU_KT6Qs63qMbOYmR3ohadwYbJZg; sid_guard=4de3b81e02deed8b692f0f0db7954999%7C1671766303%7C31536000%7CSat%2C+23-Dec-2023+03%3A31%3A43+GMT; uid_tt=ae0321af0ee558bc5e0008c94ed81815; uid_tt_ss=ae0321af0ee558bc5e0008c94ed81815; sid_tt=4de3b81e02deed8b692f0f0db7954999; sessionid=4de3b81e02deed8b692f0f0db7954999; sessionid_ss=4de3b81e02deed8b692f0f0db7954999; sid_ucp_v1=1.0.0-KGQyMjJjMzZiMmNkMzBjMTNkMGIxNjJlM2U1MTI5NTM2YWZhZDIwN2YKFwi-tMCds4z1BBCfwpSdBhiwFDgCQO8HGgJsZiIgNGRlM2I4MWUwMmRlZWQ4YjY5MmYwZjBkYjc5NTQ5OTk; ssid_ucp_v1=1.0.0-KGQyMjJjMzZiMmNkMzBjMTNkMGIxNjJlM2U1MTI5NTM2YWZhZDIwN2YKFwi-tMCds4z1BBCfwpSdBhiwFDgCQO8HGgJsZiIgNGRlM2I4MWUwMmRlZWQ4YjY5MmYwZjBkYjc5NTQ5OTk; _tea_utm_cache_2608={%22utm_source%22:%22web1%22%2C%22utm_medium%22:%22feed%22%2C%22utm_campaign%22:%22tlgt2023%22}; _gid=GA1.2.1222304144.1673582565
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
  SeaGold:
    needs: CheckIn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn seagold
